import { Ingredient } from '../types/ingredient';

export interface IngredientDetails {
  name: string;
  available: boolean;
}

export const Ingredients: Record<Ingredient, IngredientDetails> = {
  [Ingredient.Vodka]: { name: 'Vodka', available: true },
  [Ingredient.Tequila]: { name: 'Tequila', available: true },
  [Ingredient.Whiskey]: { name: 'Whiskey', available: true },
  [Ingredient.Rum]: { name: 'Rum', available: false },
  [Ingredient.WhiteRum]: { name: 'White Rum', available: true },
  [Ingredient.Gin]: { name: 'Gin', available: true },
  [Ingredient.LemonVodka]: { name: 'Lemon Vodka', available: false },
  [Ingredient.TripleSec]: { name: 'Triple Sec', available: true },
  [Ingredient.BlueCuracao]: { name: 'Blue Curacao', available: true },
  [Ingredient.LimeJuice]: { name: 'Lime Juice', available: true },
  [Ingredient.CranberryJuice]: { name: 'Cranberry Juice', available: true },
  [Ingredient.OrangeJuice]: { name: 'Orange Juice', available: true },
  [Ingredient.AppleJuice]: { name: 'Apple Juice', available: false },
  [Ingredient.TomatoJuice]: { name: 'Tomato Juice', available: true },
  [Ingredient.LemonJuice]: { name: 'Lemon Juice', available: true },
  [Ingredient.PineappleJuice]: { name: 'Pineapple Juice', available: true },
  [Ingredient.BloodOrangeJuice]: {
    name: 'Blood Orange Juice',
    available: true,
  },
  [Ingredient.OrangeLiqueur]: { name: 'Orange Liqueur', available: false },
  [Ingredient.MelonLiqueur]: { name: 'Melon Liqueur', available: false },
  [Ingredient.BananaLiqueur]: { name: 'Banana Liqueur', available: false },
  [Ingredient.AlmondLiqueur]: { name: 'Almond Liqueur', available: false },
  [Ingredient.Coffee]: { name: 'Coffee', available: false },
  [Ingredient.CoffeeLiqueur]: { name: 'Coffee Liqueur', available: false },
  [Ingredient.DryVermouth]: { name: 'Dry Vermouth', available: false },
  [Ingredient.PeachSchnapps]: { name: 'Peach Schnapps', available: true },
  [Ingredient.IrishCream]: { name: 'Irish Cream', available: true },
  [Ingredient.CremeDeCacao]: { name: 'Creme De Cacao', available: true },
  [Ingredient.Cola]: { name: 'Cola', available: true },
  [Ingredient.GrapefruitSoda]: { name: 'Grapefruit Soda', available: false },
  [Ingredient.Tonic]: { name: 'Tonic', available: true },
  [Ingredient.Ice]: { name: 'Ice', available: true },
  [Ingredient.Salt]: { name: 'Salt', available: true },
  [Ingredient.Sugar]: { name: 'Sugar', available: true },
  [Ingredient.BlackPepper]: { name: 'Black Pepper', available: true },
  [Ingredient.TajinPowder]: { name: 'Tajin Powder', available: true },
  [Ingredient.SimpleSyrup]: { name: 'Simple Syrup', available: true },
  [Ingredient.GrenadineSyrup]: { name: 'Grenadine Syrup', available: true },
  [Ingredient.CoconutSyrup]: { name: 'Coconut Syrup', available: true },
  [Ingredient.HoneySyrup]: { name: 'Honey Syrup', available: true },
  [Ingredient.WhippedCream]: { name: 'Whipped Cream', available: false },
  [Ingredient.FreshCream]: { name: 'Fresh Cream', available: true },
  [Ingredient.IceCream]: { name: 'Ice Cream', available: false },
  [Ingredient.AlmondSyrup]: { name: 'Almond Syrup', available: false },
  [Ingredient.SweetAndSour]: { name: 'Sweet And Sour', available: false },
  [Ingredient.Water]: { name: 'Water', available: true },
  [Ingredient.SodaWater]: { name: 'Soda Water', available: true },
  [Ingredient.GingerBeer]: { name: 'Ginger Beer', available: true },
  [Ingredient.MintLeaves]: { name: 'Mint Leaves', available: true },
  [Ingredient.Hpnotiq]: { name: 'Hpnotiq', available: false },
  [Ingredient.Jagermeister]: { name: 'Jagermeister', available: true },
  [Ingredient.Oreos]: { name: 'Oreos', available: false },
  [Ingredient.Olives]: { name: 'Olives', available: false },
  [Ingredient.Jalapenos]: { name: 'Jalapenos', available: true },
  [Ingredient.TabascoSauce]: { name: 'Tabasco Sauce', available: true },
};
